import { expect, test } from '@playwright/test'
import { academicMock, login, user } from './helpers/academicMock'
import type { Course } from '../src/types'

const materialId = 'navigation-material'
const course: Course = { id: 'navigation-course', name: 'Física', emoji: '⚛️', materials: [{ id: materialId, title: 'Energía y movimiento', text: 'La energía cinética depende de la masa y del cuadrado de la velocidad. La energía se conserva en un sistema aislado.', sourceType: 'pdf', pageCount: 4, pages: [{ page: 2, text: 'La energía cinética depende de la masa y la velocidad.' }], createdAt: '2026-10-01T12:00:00Z', analysisStatus: 'ready', analyzedPages: [1, 2, 3, 4],
  chunks: [{ id: 'navigation-chunk', materialId, text: 'La energía cinética depende de la masa y la velocidad.', pageStart: 2, pageEnd: 2, keywords: ['energía'] }],
  topics: [{ id: 'navigation-topic', materialId, title: 'Energía cinética', summary: 'Energía del movimiento.', pageStart: 2, pageEnd: 2, keywords: ['energía'] }],
  artifacts: [{ id: 'navigation-artifact', sourceMaterialId: materialId, type: 'flashcards', status: 'ready', version: 1, createdAt: '2026-10-01T12:00:00Z', updatedAt: '2026-10-01T12:00:00Z', payload: { scope: { page: 2 }, cards: [{ front: '¿De qué depende la energía cinética?', back: 'De la masa y del cuadrado de la velocidad.' }] } }],
}] }

test('profile utilities use the real role, save the profile and submit optional feedback context', async ({ page }) => {
  const mock = await academicMock(page)
  mock.rows.set('profiles', new Map([[user.id, { id: user.id, full_name: 'Sebastian Shulla', username: 'sebasshulla', is_admin: false }]]))
  await login(page)
  await page.getByRole('button', { name: 'Mi cuenta' }).click()
  const menu = page.getByRole('menu', { name: 'Opciones de tu cuenta' })
  await expect(menu).toContainText('@sebasshulla')
  await expect(menu.getByRole('menuitem')).toHaveText(['Mi perfil', 'Configuración', 'Apariencia', 'Enviar comentarios', 'Ayuda / Guía rápida', 'Cerrar sesión'])
  await expect(menu.getByRole('menuitem', { name: 'Administración' })).toHaveCount(0)
  await page.keyboard.press('ArrowDown')
  await expect(menu.getByRole('menuitem', { name: 'Configuración' })).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('button', { name: 'Mi cuenta' })).toBeFocused()
  await page.getByRole('button', { name: 'Mi cuenta' }).click()
  await menu.getByRole('menuitem', { name: 'Mi perfil' }).click()
  await page.getByLabel('Nombre completo').fill('Sebastian Paolo Shulla Garcia')
  await page.getByRole('button', { name: 'Guardar perfil' }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  const update = mock.requests.find(request => request.table === 'profiles' && request.method === 'PATCH')
  expect(update?.body).toEqual({ full_name: 'Sebastian Paolo Shulla Garcia' })
  await page.reload()
  await page.getByRole('button', { name: 'Mi cuenta' }).click()
  await expect(menu).toContainText('Sebastian Paolo Shulla Garcia')
  await menu.getByRole('menuitem', { name: 'Apariencia' }).click()
  await page.getByLabel('Reducir las transiciones').check()
  await page.getByRole('button', { name: 'Listo', exact: true }).click()
  await expect(page.locator('html')).toHaveAttribute('data-reduced-motion', 'true')
  for (const include of [false, true]) {
    await page.getByRole('button', { name: 'Mi cuenta' }).click()
    await menu.getByRole('menuitem', { name: 'Enviar comentarios' }).click()
    const dialog = page.getByRole('dialog', { name: '¿Qué podríamos mejorar?' })
    await dialog.getByRole('textbox', { name: 'Tu comentario' }).fill('Quiero poder encontrar mis materiales con menos pasos.')
    if (include) await dialog.getByLabel('Incluir información técnica de esta pantalla').check()
    await dialog.getByRole('button', { name: 'Enviar comentario' }).click()
    await expect(dialog).toContainText('¡Gracias!')
    const submitted = mock.requests.filter(request => request.table === 'feedback_entries' && request.method === 'POST').slice(-1)[0].body as Record<string, unknown>
    expect(submitted.page_context).toBe(include ? '/' : null)
    expect(Boolean(submitted.user_agent)).toBe(include)
    await dialog.getByRole('button', { name: 'Volver a Nexo' }).click()
  }
  await expect(page.locator('.feedback-fab')).toHaveCount(0)
})

test('admin utilities appear only after a verified profile flag and the console keeps its gate', async ({ page }) => {
  const mock = await academicMock(page)
  mock.rows.set('profiles', new Map([[user.id, { id: user.id, full_name: 'Sebastian', username: 'sebasshulla', is_admin: true }]]))
  await login(page)
  await page.getByRole('button', { name: 'Mi cuenta' }).click()
  const menu = page.getByRole('menu', { name: 'Opciones de tu cuenta' })
  await expect(menu.getByRole('menuitem', { name: 'Administración', exact: true })).toBeVisible()
  await expect(menu.getByRole('menuitem', { name: 'Feedback recibido' })).toBeVisible()
  await menu.getByRole('menuitem', { name: 'Administración', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Comentarios de Nexo' })).toBeVisible()
  mock.rows.get('profiles')!.get(user.id)!.is_admin = false
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Página no encontrada' })).toBeVisible()
})

test('palette supports keyboard, recent destinations, scoped resources and persisted Resolver conversations', async ({ page }) => {
  const mock = await academicMock(page)
  mock.seedCourse(course)
  mock.rows.get('study_artifacts')!.get('navigation-artifact')!.scope = { page: 2 }
  await login(page)
  await page.keyboard.press('Control+k')
  const dialog = page.getByRole('dialog', { name: 'Buscar en Nexo Study' })
  const input = dialog.getByRole('combobox')
  await input.fill('Física')
  await input.press('Enter')
  await expect(page).toHaveURL(/\/courses\/navigation-course$/)
  await page.keyboard.press('Meta+k')
  await expect(dialog).toContainText('Reciente')
  await expect(dialog.getByRole('option', { name: /Física/ })).toBeVisible()
  await input.fill('flashcards')
  await expect(dialog.getByRole('option', { name: /Flashcards/ }).first()).toBeVisible()
  await input.press('Enter')
  await expect(page).toHaveURL(/\/materials\/navigation-material\/workspace$/)
  await expect(page.locator('.material-workspace-head')).toContainText('Página 2')
  if (page.viewportSize()!.width <= 700) await expect(page.locator('.study-focus-shell')).toBeVisible()
  await expect(page.locator('.page-artifact-view')).toBeVisible()
  await page.goto('/resolver')
  await page.route('**/api/ai/solve', route => route.fulfill({ json: { text: 'La energía cinética es la energía del movimiento.' } }))
  await page.getByRole('textbox', { name: 'Escribe tu pregunta' }).fill('Explica la energía cinética con un ejemplo')
  await page.getByRole('button', { name: 'Enviar pregunta' }).click()
  await expect(page.locator('.solver-assistant-bubble')).toContainText('energía del movimiento')
  await page.getByRole('button', { name: 'Nuevo chat' }).click()
  await page.keyboard.press('Control+k')
  await input.fill('cinética con un ejemplo')
  await expect(dialog.getByRole('option', { name: /Resolver/ })).toBeVisible()
  await input.press('Enter')
  await expect(page.locator('.solver-assistant-bubble')).toContainText('energía del movimiento')
  await expect(page.locator('.solver-empty')).toHaveCount(0)
})

test('context menus rename without rewriting material bodies and courses move through existing memberships', async ({ page }) => {
  const mock = await academicMock(page)
  mock.seedCourse(course)
  mock.rows.set('study_folders', new Map([['folder-target', { id: 'folder-target', user_id: user.id, name: 'Universidad', emoji: '🎓', created_at: '2026-10-01T00:00:00Z' }]]))
  await login(page)
  await page.goto('/courses')
  await page.getByRole('button', { name: 'Opciones de Física' }).click()
  await page.getByRole('menuitem', { name: 'Editar curso' }).click()
  await page.getByLabel('Nombre del curso').fill('Física aplicada')
  await page.getByRole('button', { name: 'Guardar', exact: true }).click()
  await expect(page.locator('.course-library-grid')).toContainText('Física aplicada')
  await page.getByRole('button', { name: /⚛️ Física aplicada/ }).click()
  await page.getByRole('button', { name: 'Opciones de Energía y movimiento' }).click()
  await page.getByRole('menuitem', { name: 'Renombrar', exact: true }).click()
  await page.getByLabel('Título del material').fill('Energía cinética y potencial')
  await page.getByRole('button', { name: 'Guardar', exact: true }).click()
  await expect(page.locator('.course-materials-grid')).toContainText('Energía cinética y potencial')
  const patch = mock.requests.filter(request => request.table === 'materials' && request.method === 'PATCH').slice(-1)[0]
  expect(patch.body).toEqual({ title: 'Energía cinética y potencial' })
  await page.goto('/courses')
  await page.getByRole('button', { name: 'Opciones de Física aplicada' }).click()
  await page.getByRole('menuitem', { name: 'Mover a espacio' }).click()
  await page.getByLabel('Espacio de destino').selectOption('folder-target')
  await page.getByRole('button', { name: 'Guardar', exact: true }).click()
  await expect(page.locator('.context-strip')).toContainText('Universidad')
  await expect(page.locator('.course-library-grid')).toContainText('Física aplicada')
  expect(mock.requests.some(request => request.table === 'folder_courses' && request.method === 'POST')).toBeTruthy()
})

test('visual QA covers all eight viewports with one navigation, accessible menus and no overflow', async ({ page }, info) => {
  test.setTimeout(180000)
  const mock = await academicMock(page)
  mock.seedCourse(course)
  for (const [index, name] of ['Química', 'Anatomía', 'Matemáticas', 'Biología'].entries()) mock.seedCourse({ id: `course-grid-${index}`, name, emoji: '📚', materials: [] })
  const visit = (path: string) => page.evaluate(target => { history.pushState({}, '', target); dispatchEvent(new PopStateEvent('popstate')) }, path)
  await login(page)
  for (const [width, height] of [[320, 640], [375, 667], [393, 852], [430, 932], [768, 1024], [1366, 768], [1440, 900], [1920, 1080]]) {
    await page.setViewportSize({ width, height })
    const screenshot = async (name: string) => {
      await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width + 1)
      await page.screenshot({ path: info.outputPath(`${name}-${width}.png`), fullPage: true, animations: 'disabled' })
    }
    await visit('/')
    await expect(page.locator('.home-page')).toBeVisible()
    await expect(page.locator('.mobile-nav, .workspace-edge-trigger, .feedback-fab')).toHaveCount(0)
    await screenshot('home')
    await page.getByRole('button', { name: 'Mi cuenta' }).click()
    await expect(page.getByRole('menu', { name: 'Opciones de tu cuenta' })).toBeVisible()
    await screenshot('profile')
    await page.keyboard.press('Escape')
    await page.keyboard.press('Control+k')
    await page.getByRole('combobox').fill('Física')
    await expect(page.getByRole('option').first()).toBeVisible()
    await screenshot('search')
    await page.keyboard.press('Escape')
    if (width <= 700) {
      await page.getByRole('button', { name: 'Abrir navegación' }).click()
      const drawer = page.getByRole('dialog', { name: 'Barra lateral principal' })
      const bounds = (await drawer.boundingBox())!
      expect(bounds.width).toBeLessThanOrEqual(Math.min(320, width * .84) + 1)
      await expect(page.locator('body')).toHaveCSS('overflow', 'hidden')
      await expect(page.locator('main')).toHaveAttribute('inert', '')
      await screenshot('drawer')
      await drawer.getByRole('button', { name: 'Mis cursos', exact: true }).click()
      await expect(drawer).toBeHidden()
      await expect(page.locator('main')).not.toHaveAttribute('inert', '')
      await page.getByRole('button', { name: 'Abrir navegación' }).click()
      await page.locator('.mobile-sidebar-backdrop').click({ position: { x: width - 4, y: 60 } })
      await expect(drawer).toBeHidden()
      if (width === 393) {
        await page.getByRole('button', { name: 'Abrir navegación' }).click()
        await drawer.getByRole('button', { name: /Cambiar espacio de estudio/ }).click()
        const spaces = page.getByRole('dialog', { name: 'Explorador de espacios' })
        await spaces.getByRole('group', { name: 'Espacios de estudio' }).getByRole('button', { name: /General/ }).click()
        await expect(drawer).toBeHidden()
        await expect(page.locator('body')).toHaveCSS('overflow', 'hidden')
        await spaces.getByRole('button', { name: 'Cerrar explorador de espacios' }).click()
        await expect(page.locator('body')).not.toHaveCSS('overflow', 'hidden')
      }
    }
    await visit('/courses')
    await expect(page.locator('.course-library-grid')).toBeVisible()
    const columns = await page.locator('.course-library-grid').evaluate(node => getComputedStyle(node).gridTemplateColumns.split(' ').length)
    expect(columns).toBe(width <= 700 ? 1 : width >= 1500 ? 3 : 2)
    await screenshot('courses')
    await visit('/resolver')
    await expect(page.locator('.nexo-composer')).toBeVisible()
    await page.getByRole('textbox', { name: 'Escribe tu pregunta' }).fill('Explícame un ejercicio paso a paso')
    await page.getByRole('textbox', { name: 'Escribe tu pregunta' }).focus()
    await screenshot('resolver')
    await visit(`/courses/${course.id}/materials/${materialId}/workspace`)
    await expect(page.locator('.material-workspace')).toBeVisible()
    await screenshot('material')
    if (width <= 700) { await expect(page.locator('.material-nexo-panel')).toBeHidden(); await page.getByRole('tab', { name: 'Nexo IA' }).click(); await expect(page.locator('.material-document')).toBeHidden() }
    await page.getByRole('tab', { name: 'Chat', exact: true }).click()
    await expect(page.locator('.material-chat-composer.nexo-composer')).toBeVisible()
    await screenshot('material-chat')
  }
})
