import { openGlobalSearch } from './helpers/navigation'
import { expect, test, type Page } from '@playwright/test'
import { academicMock, login, png, user } from './helpers/academicMock'
import { applyEvidence, makeEvidence, getRecommendedConcepts, courseConcepts } from '../src/lib/learningGraph'
import { buildMemoryContext, contextBudgets, matchQuestionConcept } from '../src/lib/learningMemory'
import { masterySummary } from '../src/lib/learningState'
import { todayActions } from '../src/lib/productIntelligence'
import type { Course } from '../src/types'
import type { ConversationMessage } from '../src/lib/conversationTypes'

import { graphCourse, now, question } from './helpers/learningFixture'
const workspace = '/courses/course-graph/materials/material-graph/workspace'
async function prepare(page: Page) {
  const mock = await academicMock(page); mock.seedCourse(graphCourse)
  const aiPayloads: Record<string,unknown>[] = []
  page.on('request',request=>{ if(request.url().endsWith('/api/ai/solve')) aiPayloads.push(request.postDataJSON()) })
  await page.route('**/api/ai/solve', route => route.fulfill({ json: { text: route.request().postDataJSON().task === 'artifact' ? JSON.stringify({ questions: [question, { ...question, question: '¿Qué componente vale cero?' }, { ...question, question: '¿Por qué la rapidez no es cero?' }] }) : 'La componente horizontal permanece en el vértice.' } }))
  await login(page)
  return {...mock,aiPayloads}
}
async function resolve(page: Page, text: string) {
  await page.getByRole('textbox', { name: 'Escribe tu pregunta' }).fill(text)
  await page.getByRole('button', { name: 'Enviar pregunta' }).click()
  await expect(page.locator('.solver-assistant-bubble').last()).toContainText('horizontal')
}
async function openMaterialChat(page: Page) {
  await page.goto(workspace)
  if (page.viewportSize()!.width <= 700) await page.getByRole('tab', { name: 'Nexo' }).click()
  await page.getByRole('tab', { name: 'Chat', exact: true }).click()
}
test('remote conversation survives without local cache; two histories restore the selected thread', async ({ page }) => {
  const mock = await prepare(page)
  await page.goto('/resolver'); await resolve(page, 'Velocidad mínima en parabólico')
  await expect.poll(() => mock.rows.get('conversation_messages')?.size).toBe(2)
  const firstId = [...mock.rows.get('conversation_threads')!.keys()][0]
  await page.getByRole('button', { name: 'Nuevo chat' }).click()
  await resolve(page, 'Componentes de la velocidad')
  await expect.poll(() => mock.rows.get('conversation_threads')?.size).toBe(2)
  await page.getByRole('button', { name: 'Mostrar conversaciones' }).click()
  const history = page.getByRole('dialog', { name: 'Conversaciones recientes' })
  await expect(history.locator('.conversation-history-row')).toHaveCount(2)
  await history.getByRole('button', { name: /Velocidad mínima/ }).click()
  await expect(page.locator('.solver-user-bubble')).toContainText('Velocidad mínima')
  await page.reload(); await expect(page.locator('.solver-user-bubble')).toContainText('Velocidad mínima')
  await page.evaluate(id => { for (const key of Object.keys(localStorage)) if (key.startsWith(`nexo-conversations-v1:${id}`)) localStorage.removeItem(key) }, user.id)
  await page.reload(); await page.getByRole('button', { name: 'Mostrar conversaciones' }).click()
  await history.getByRole('button', { name: /Velocidad mínima/ }).click()
  await expect(page.locator('.solver-assistant-bubble')).toContainText('horizontal')
  expect(mock.requests.filter(item => item.table === 'conversation_messages' && item.method === 'GET').every(item => new URL(item.url).searchParams.get('limit') === '41')).toBe(true)
  expect(firstId).toBeTruthy()
})
test('rename archive restore and explicit deletion update history and remove the remote messages', async ({ page }) => {
  const mock = await prepare(page)
  await page.goto('/resolver'); await resolve(page, 'Una conversación que renombraré')
  await expect.poll(() => mock.rows.get('conversation_messages')?.size).toBe(2)
  await page.getByRole('button', { name: 'Mostrar conversaciones' }).click()
  const history = page.getByRole('dialog', { name: 'Conversaciones recientes' })
  await history.getByLabel('Acciones de Una conversación que renombraré').click()
  await history.getByRole('button', { name: 'Renombrar', exact: true }).click()
  const rename = page.getByRole('dialog', { name: 'Renombrar conversación' })
  await rename.getByLabel('Título').fill('Vértice del movimiento'); await rename.getByRole('button', { name: 'Guardar título' }).click()
  await expect(history.getByRole('button', { name: /Vértice del movimiento/ })).toBeVisible()
  await history.getByLabel('Acciones de Vértice del movimiento').click(); await history.getByRole('button', { name: 'Archivar', exact: true }).click()
  await expect(history.locator('.conversation-history-row')).toHaveCount(0)
  await history.getByRole('button', { name: 'Archivadas', exact: true }).click()
  await history.getByLabel('Acciones de Vértice del movimiento').click(); await history.getByRole('button', { name: 'Restaurar' }).click()
  await history.getByRole('button', { name: 'Ver activas' }).click()
  await history.getByLabel('Acciones de Vértice del movimiento').click()
  page.once('dialog', dialog => dialog.accept()); await history.getByRole('button', { name: 'Eliminar', exact: true }).click()
  await expect(history.locator('.conversation-history-row')).toHaveCount(0)
  expect(mock.rows.get('conversation_threads')?.size).toBe(0); expect(mock.rows.get('conversation_messages')?.size).toBe(0)
})
test('offline append preserves the chat and retries idempotently, including private images', async ({ page }) => {
  const mock = await prepare(page); mock.control.failConversation = true
  await page.goto('/resolver')
  await page.locator('.solver-composer input[type=file]').setInputFiles({ name: 'ejercicio.png', mimeType: 'image/png', buffer: png })
  await resolve(page, '¿Qué significa la velocidad horizontal?')
  await expect(page.locator('.conversation-sync-notice')).toContainText('No pudimos sincronizar')
  await page.reload(); await expect(page.locator('.solver-assistant-bubble')).toContainText('horizontal')
  await expect(page.locator('.conversation-sync-notice')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Reintentar sincronización', exact: true })).toBeEnabled()
  mock.control.failConversation = false
  await page.getByRole('button', { name: 'Reintentar sincronización', exact: true }).click()
  await expect.poll(() => mock.rows.get('conversation_messages')?.size).toBe(2)
  await expect(page.locator('.conversation-sync-notice')).toHaveCount(0)
  const message = [...mock.rows.get('conversation_messages')!.values()].find(item => item.role === 'user')!
  expect((message.metadata as { attachmentsReady: boolean }).attachmentsReady).toBe(true)
  expect(mock.conversationUploaded).toHaveLength(1)
  await page.reload(); expect(mock.rows.get('conversation_messages')?.size).toBe(2)
})
test('course and material chats persist exact context and sources; global search opens their scope', async ({ page }) => {
  const mock = await prepare(page)
  await page.goto('/courses/course-graph/ai')
  await page.getByRole('textbox', { name: 'Preguntar sobre el curso' }).fill('¿Cómo funciona el Movimiento parabólico?')
  await page.getByRole('button', { name: 'Preguntar a Nexo' }).click()
  await expect(page.locator('.material-chat-answer')).toContainText('horizontal')
  await expect.poll(() => [...(mock.rows.get('conversation_threads')?.values() ?? [])].some(row => row.scope === 'course' && row.course_id === graphCourse.id && row.material_id === null)).toBe(true)
  await openMaterialChat(page)
  await page.getByRole('textbox', { name: 'Preguntar sobre este material' }).fill('¿Por qué en Movimiento parabólico vy es cero?')
  await page.getByRole('button', { name: 'Preguntar a Nexo' }).click()
  await expect(page.locator('.material-chat-answer')).toContainText('horizontal')
  await expect.poll(() => [...(mock.rows.get('conversation_threads')?.values() ?? [])].some(row => row.scope === 'material' && row.material_id === 'material-graph')).toBe(true)
  await page.reload()
  if (page.viewportSize()!.width <= 700) await page.getByRole('tab', { name: 'Nexo' }).click()
  await page.getByRole('tab', { name: 'Chat', exact: true }).click()
  await expect(page.locator('.material-chat-sources')).toContainText('página 2')
  await openGlobalSearch(page)
  await page.getByRole('combobox').fill('Movimiento parabólico')
  await expect(page.getByRole('option').filter({ hasText: 'curso' }).or(page.getByRole('option').filter({ hasText: 'Física conectada' })).first()).toBeVisible()
  await page.getByRole('option').filter({ hasText: '¿Por qué en Movimiento' }).click()
  await expect(page.locator('.material-chat-answer')).toContainText('horizontal')
  expect(mock.requests.filter(item => item.table === 'conversation_threads' && item.method === 'GET').some(item => new URL(item.url).searchParams.has('ilike') || new URL(item.url).searchParams.get('title')?.startsWith('ilike.'))).toBe(true)
})
test('wrong quiz closes the learning loop through Nexo, focused practice, Home and concept detail', async ({ page }) => {
  const mock = await prepare(page)
  await page.goto('/courses/course-graph/materials/material-graph/study/multiple-choice')
  await page.locator('.quiz-card .options button').nth(1).click()
  await expect.poll(() => mock.rows.get('concept_evidence')?.size).toBe(1)
  expect([...mock.rows.get('concept_evidence')!.values()][0]).toMatchObject({ source_type: 'quiz', result: 'again', concept_key: 'movimiento-parabolico' })
  await page.getByRole('button', { name: 'Preguntar a Nexo' }).click()
  await expect(page.getByRole('textbox', { name: 'Preguntar sobre este material' })).toHaveValue('Ayúdame a entender este error.')
  await page.getByRole('button', { name: 'Preguntar a Nexo' }).click()
  await expect(page.locator('.material-chat-answer')).toContainText('horizontal')
  const solve = mock.aiPayloads.filter(item=>item.task==='solve').slice(-1)[0]
  expect(solve).toMatchObject({courseId:graphCourse.id,materialId:'material-graph',page:2})
  expect(String(solve.context)).toContain('Movimiento parabólico')
  expect(String(solve.context)).toContain('Vertical')
  expect(String(solve.context)).toContain('Horizontal')
  expect(String(solve.context)).toContain(question.question)
  await page.getByRole('button', { name: 'Practicar esto', exact: true }).click()
  const practice = page.getByRole('dialog', { name: 'Practicar con Nexo' })
  await practice.getByRole('button', { name: 'Preparar práctica', exact: true }).click()
  await expect(practice.locator('.quiz-card')).toHaveCount(page.viewportSize()!.width <= 700 ? 1 : 3)
  await practice.locator('.quiz-card .options button').first().click()
  await expect.poll(() => mock.rows.get('concept_evidence')?.size).toBe(2)
  await practice.getByRole('button', { name: 'Cerrar diálogo' }).click()
  await page.goto('/progress')
  await page.locator('.concept-state-list button').filter({ hasText: 'Movimiento parabólico' }).click()
  const detail = page.getByRole('dialog', { name: 'Concepto: Movimiento parabólico' })
  await expect(detail).toContainText('2 prácticas')
  await expect(detail.locator('.concept-evidence-list')).toContainText('Quiz')
  await detail.getByRole('button', { name: 'Cerrar diálogo' }).click()
  await page.goto('/')
  await expect(page.locator('.home-today-actions')).toContainText('Movimiento parabólico')
  expect([...mock.rows.get('study_artifacts')!.values()].filter(item => (item.payload as { scope?: { kind?: string } }).scope?.kind === 'concept')).toHaveLength(1)
})
test('hard flashcard feeds evidence immediately and profile can erase a signal', async ({ page }) => {
  const mock = await prepare(page)
  await page.goto('/courses/course-graph/materials/material-graph/study/flashcards')
  await page.locator('.flashcard').click(); await page.getByRole('button', { name: 'Difícil', exact: true }).click()
  await expect.poll(() => mock.rows.get('concept_evidence')?.size).toBe(1)
  await page.goto('/progress'); await expect(page.locator('.concept-state-list')).toContainText('En aprendizaje')
  await page.getByRole('button', { name: 'Mi cuenta', exact: true }).click(); await page.getByRole('menuitem', { name: 'Mi perfil' }).click()
  await page.getByRole('button', { name: 'Ver memoria' }).click()
  const memory = page.getByRole('dialog', { name: 'Datos y memoria de Nexo' })
  await memory.getByRole('button', { name: /Movimiento parabólico/ }).click()
  page.once('dialog', dialog => dialog.accept()); await page.getByRole('button', { name: 'Eliminar señal', exact: true }).click()
  await expect.poll(() => mock.rows.get('concept_evidence')?.size).toBe(0)
  await page.getByRole('dialog', { name: 'Concepto: Movimiento parabólico' }).getByRole('button', { name: 'Cerrar diálogo' }).click()
  await expect(memory).toContainText('No hay suficiente evidencia')
})
test('history traps mobile focus, closes on Escape and the composer has no 320px overflow', async ({ page }) => {
  await prepare(page); await page.setViewportSize({ width: 320, height: 640 }); await page.goto('/resolver'); await resolve(page, 'Pregunta con velocidad horizontal')
  await page.getByRole('button', { name: 'Mostrar conversaciones' }).click()
  const history = page.getByRole('dialog', { name: 'Conversaciones recientes' })
  await expect(history).toBeVisible(); await expect(history.getByRole('searchbox')).toBeFocused()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
  await page.keyboard.press('Escape'); await expect(history).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Mostrar conversaciones' })).toBeFocused()
  await page.getByRole('textbox', { name: 'Escribe tu pregunta' }).focus()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
  await expect(page.getByRole('textbox', { name: 'Escribe tu pregunta' })).toBeInViewport()
})
test('paginated history and inverse message pages do not fetch the full account history', async ({ page }) => {
  const mock = await prepare(page)
  const threads = mock.rows.get('conversation_threads') ?? new Map(); mock.rows.set('conversation_threads', threads)
  const messages = mock.rows.get('conversation_messages') ?? new Map(); mock.rows.set('conversation_messages', messages)
  const id = crypto.randomUUID()
  for (let i=0; i<29; i++) { const threadId = i === 0 ? id : crypto.randomUUID(); threads.set(threadId, { id: threadId, user_id: user.id, scope: 'general', workspace_id: null, course_id: null, material_id: null, title: `Historial ${i}`, created_at: now, updated_at: now, last_message_at: new Date(Date.now()-i*1000).toISOString(), archived_at: null }) }
  for (let i=0; i<83; i++) { const messageId = crypto.randomUUID(); messages.set(messageId, { id: messageId, thread_id: id, user_id: user.id, role: i%2 ? 'assistant' : 'user', content: `Mensaje número ${i}`, created_at: new Date(Date.parse(now)+i*1000).toISOString(), metadata: {} }) }
  await page.goto('/resolver'); await page.getByRole('button', { name: 'Mostrar conversaciones' }).click()
  const history = page.getByRole('dialog', { name: 'Conversaciones recientes' })
  await expect(history.locator('.conversation-history-row')).toHaveCount(25)
  await history.getByRole('button', { name: 'Cargar más conversaciones' }).click(); await expect(history.locator('.conversation-history-row')).toHaveCount(29)
  await history.getByRole('button', { name: /Historial 0/, exact: false }).click()
  await expect(page.locator('.solver-turn')).toHaveCount(40)
  await page.getByRole('button', { name: 'Cargar anteriores' }).click(); await expect(page.locator('.solver-turn')).toHaveCount(80)
  await page.getByRole('button', { name: 'Cargar anteriores' }).click(); await expect(page.locator('.solver-turn')).toHaveCount(83)
})
test('mock server denies another owner reading writing searching and relating private data', async ({ page, browser }) => {
  const mock = await prepare(page); await page.goto('/resolver'); await resolve(page, 'Secreto parabólico de A')
  await expect.poll(() => mock.rows.get('conversation_messages')?.size).toBe(2)
  const thread = [...mock.rows.get('conversation_threads')!.values()][0]
  const otherContext = await browser.newContext(); const other = await otherContext.newPage()
  const identity = { ...user, id: '87654321-4321-4321-8321-210987654321', email: 'usuario-b@example.com' }
  await academicMock(other, { identity, rows: mock.rows }); await login(other)
  const results = await other.evaluate(async ({ id, owner, courseId, materialId }) => {
    const base = 'https://nexo-test.supabase.co/rest/v1/'
    const query = `?user_id=eq.${owner}&id=eq.${id}`
    const headers = { 'Content-Type': 'application/json', Authorization: 'Bearer test-b', apikey: 'test-public-key' }
    const read = await (await fetch(`${base}conversation_threads${query}`, { headers })).json()
    const messages = await (await fetch(`${base}conversation_messages?thread_id=eq.${id}`, { headers })).json()
    const edit = await (await fetch(`${base}conversation_threads${query}`, { method: 'PATCH', headers, body: JSON.stringify({ title: 'Intrusión' }) })).json()
    const remove = await (await fetch(`${base}conversation_threads${query}`, { method: 'DELETE', headers })).json()
    const insert = await fetch(`${base}rpc/append_conversation_message`, { method: 'POST', headers, body: JSON.stringify({ p_thread: { id: crypto.randomUUID(), scope: 'material', course_id: courseId, material_id: materialId, title: 'Ajeno', workspace_id: null }, p_message: { id: crypto.randomUUID(), role: 'user', content: 'Intrusión', metadata: {} } }) })
    const evidence = await fetch(`${base}rpc/record_concept_evidence`, { method: 'POST', headers, body: JSON.stringify({ p_evidence: { id: crypto.randomUUID(), course_id: courseId, material_id: materialId, concept_key: 'privado', concept_label: 'Privado', source_type: 'quiz', source_id: 'x', result: 'again' } }) })
    const search = await (await fetch(`${base}conversation_threads?title=ilike.*Secreto*`, { headers })).json()
    return { read, messages, edit, remove, insert: insert.status, evidence: evidence.status, search }
  }, { id: thread.id, owner: user.id, courseId: graphCourse.id, materialId: 'material-graph' })
  expect(results).toEqual({ read: [], messages: [], edit: [], remove: [], insert: 403, evidence: 403, search: [] })
  expect(mock.rows.get('conversation_threads')!.get(String(thread.id))?.title).toBe('Secreto parabólico de A')
  await otherContext.close()
})
test('memory requires real evidence and context budgets never include unrelated courses', () => {
  const e = makeEvidence(graphCourse.id, 'material-graph', 'Movimiento parabólico', 'question', 'chat')
  const memory = applyEvidence({}, e)
  expect(applyEvidence(memory,e)).toBe(memory)
  expect(memory['material-graph:movimiento-parabolico'].attempts).toBe(0)
  expect(masterySummary(memory, ['material-graph']).sufficient).toBe(false)
  expect(getRecommendedConcepts(memory, graphCourse)).toHaveLength(0)
  expect(matchQuestionConcept('hola', graphCourse)).toBeUndefined()
  const negative = applyEvidence(memory, makeEvidence(graphCourse.id, 'material-graph', 'Movimiento parabólico', 'again', 'quiz'))
  expect(todayActions([graphCourse], {}, negative, [])[0].concept?.label).toBe('Movimiento parabólico')
  expect(courseConcepts(graphCourse, memory).some(item => item.label === 'Movimiento parabólico')).toBe(true)
  const messages: ConversationMessage[] = Array.from({ length: 500 }, (_, i) => ({ id: String(i), threadId: 'x', role: i%2 ? 'assistant' : 'user', content: `QUESTION-${i} ` + 'a'.repeat(4000), createdAt: now, metadata: {} }))
  const context = buildMemoryContext({ course: graphCourse, memory: negative, messages, retrieval: 'r'.repeat(50000), seed: 's'.repeat(8000) })
  expect(context.length).toBeLessThan(Object.values(contextBudgets).reduce((a,b) => a+b,0)+1000)
  expect(context).not.toContain('QUESTION-1 ')
  expect(buildMemoryContext({ memory: negative, messages: [] })).not.toContain('Movimiento parabólico')
})

test('reset course memory removes evidence without removing study activity or conversations', async ({ page }) => {
  const mock = await prepare(page)
  await page.goto('/courses/course-graph/materials/material-graph/study/multiple-choice')
  await page.locator('.quiz-card .options button').nth(1).click()
  await expect.poll(() => mock.rows.get('concept_evidence')?.size).toBe(1)
  await page.goto('/resolver'); await resolve(page,'Conservar mi conversación')
  await expect.poll(() => mock.rows.get('conversation_messages')?.size).toBe(2)
  await page.getByRole('button',{name:'Mi cuenta',exact:true}).click(); await page.getByRole('menuitem',{name:'Mi perfil'}).click()
  await page.getByRole('button',{name:'Ver memoria'}).click()
  const memory = page.getByRole('dialog',{name:'Datos y memoria de Nexo'})
  page.once('dialog',dialog=>dialog.accept()); await memory.getByRole('button',{name:'Reiniciar memoria del curso'}).click()
  await expect(memory).toContainText('No hay suficiente evidencia')
  expect(mock.rows.get('concept_evidence')?.size).toBe(0)
  expect(mock.rows.get('conversation_messages')?.size).toBe(2)
  expect([...mock.rows.get('learning_state')!.values()][0]).toMatchObject({attempts:0,status:'unknown',evidence_managed:true})
  await page.reload(); await expect(page.locator('.solver-assistant-bubble')).toContainText('horizontal')
})

test('draft survives reload and new conversation creates no empty remote thread', async ({page})=>{
  const mock=await prepare(page); await page.goto('/resolver')
  await page.getByRole('textbox',{name:'Escribe tu pregunta'}).fill('Mi pregunta todavía no enviada')
  await page.reload(); await expect(page.getByRole('textbox',{name:'Escribe tu pregunta'})).toHaveValue('Mi pregunta todavía no enviada')
  expect(mock.rows.get('conversation_threads')?.size ?? 0).toBe(0)
  await resolve(page,'Velocidad horizontal'); await page.getByRole('button',{name:'Nuevo chat'}).click()
  await expect(page.locator('.solver-turn')).toHaveCount(0)
  expect(mock.rows.get('conversation_threads')?.size).toBe(1)
  await page.evaluate(()=>window.dispatchEvent(new Event('focus')))
  await expect(page.locator('.solver-turn')).toHaveCount(0)
})

test('two tabs append to the same thread without overwriting or duplicating messages',async({page,context})=>{
  const mock=await prepare(page); await page.goto('/resolver'); await resolve(page,'Conversación compartida entre mis pestañas')
  await expect.poll(()=>mock.rows.get('conversation_messages')?.size).toBe(2)
  const second=await context.newPage(); await academicMock(second,{rows:mock.rows})
  await second.route('**/api/ai/solve',route=>route.fulfill({json:{text:'La velocidad horizontal permanece.'}}))
  await second.goto('/resolver'); await expect(second.locator('.solver-assistant-bubble')).toContainText('horizontal')
  await Promise.all([resolve(page,'Primera pestaña pregunta por vx'),resolve(second,'Segunda pestaña pregunta por vy')])
  await expect.poll(()=>mock.rows.get('conversation_messages')?.size).toBe(6)
  await page.evaluate(()=>window.dispatchEvent(new Event('focus')))
  await expect(page.locator('.solver-user-bubble')).toHaveCount(3)
  expect(mock.rows.get('conversation_threads')?.size).toBe(1)
  await second.close()
})

test('legacy Resolver history is migrated once and explicit delete clears the older browser copy',async({page})=>{
  const mock=await prepare(page)
  await page.evaluate(({owner,now})=>localStorage.setItem(`nexo-study-resolver-history-v4:${owner}:general`,JSON.stringify([{question:'Mi pregunta de V0.9.4',answer:'La velocidad horizontal permanece.',category:'Matemáticas',deep:true,createdAt:now}])),{owner:user.id,now})
  await page.goto('/resolver'); await expect(page.locator('.solver-assistant-bubble')).toContainText('horizontal')
  await expect.poll(()=>mock.rows.get('conversation_messages')?.size).toBe(2)
  await page.reload(); expect(mock.rows.get('conversation_threads')?.size).toBe(1)
  await page.getByRole('button',{name:'Mostrar conversaciones'}).click()
  const history=page.getByRole('dialog',{name:'Conversaciones recientes'})
  await history.getByLabel('Acciones de Mi pregunta de V0.9.4').click()
  page.once('dialog',dialog=>dialog.accept()); await history.getByRole('button',{name:'Eliminar',exact:true}).click()
  await expect(history.locator('.conversation-history-row')).toHaveCount(0)
  await expect.poll(()=>page.evaluate(owner=>JSON.parse(localStorage.getItem(`nexo-study-resolver-history-v4:${owner}:general`)??'[]').length,user.id)).toBe(0)
})


test('offline learning evidence survives hydration and retries exactly once',async({page})=>{
  const mock=await prepare(page); mock.control.failEvidence=true
  await page.goto('/courses/course-graph/materials/material-graph/study/multiple-choice')
  await page.locator('.quiz-card .options button').nth(1).click()
  await page.goto('/progress'); await page.locator('.concept-state-list button').filter({hasText:'Movimiento parabólico'}).click()
  await expect(page.getByRole('dialog',{name:'Concepto: Movimiento parabólico'})).toContainText('1 prácticas')
  await page.reload(); await page.locator('.concept-state-list button').filter({hasText:'Movimiento parabólico'}).click()
  await expect(page.getByRole('dialog',{name:'Concepto: Movimiento parabólico'})).toContainText('1 prácticas')
  mock.control.failEvidence=false
  await page.keyboard.press('Escape'); await page.evaluate(()=>window.dispatchEvent(new Event('online')))
  await expect.poll(()=>mock.rows.get('concept_evidence')?.size).toBe(1)
  expect([...mock.rows.get('learning_state')!.values()][0].attempts).toBe(1)
})

test('invalid AI response preserves question and a retry does not create a duplicate user turn',async({page})=>{
  const mock=await prepare(page); let attempt=0
  await page.route('**/api/ai/solve',route=>route.fulfill({json:attempt++ ? {text:'La velocidad horizontal permanece.'} : {text:''}}))
  await page.goto('/resolver'); await page.getByRole('textbox',{name:'Escribe tu pregunta'}).fill('Mi duda de velocidad')
  await page.getByRole('button',{name:'Enviar pregunta'}).click()
  await expect(page.getByRole('alert')).toContainText('respuesta incompleta')
  await expect(page.locator('.solver-user-bubble')).toHaveCount(1)
  await expect(page.getByRole('textbox',{name:'Escribe tu pregunta'})).toHaveValue('Mi duda de velocidad')
  await page.getByRole('button',{name:'Reintentar',exact:true}).click()
  await expect(page.locator('.solver-assistant-bubble')).toContainText('horizontal')
  await expect.poll(()=>mock.rows.get('conversation_messages')?.size).toBe(2)
})
