import type { Material } from './types'
import { displayMaterialTitle } from './lib/materialTitles'
import { PopupMenu } from './PopupMenu'
import { sourceDescription, sourceLabels } from './lib/sourceModel'

export function MaterialCard({ material, onOpen, onRename, onDownload, onArchive, onDelete, lastStudied }: { material: Material; onOpen: () => void; onRename: () => void; onDownload?: () => void; onArchive: () => void; onDelete: () => void; lastStudied?: string }) {
  return <article className="material-card-frame"><button disabled={material.deletionPending} className="material-card" onClick={onOpen}><div className="material-meta"><span className="file-icon">{sourceLabels[material.sourceType ?? 'text']}</span><small>{sourceDescription(material)}</small></div><h3>{displayMaterialTitle(material.title)}</h3><p>{material.deletionPending ? 'Eliminación pendiente de limpieza' : material.processingStatus === 'processing' || material.processingStatus === 'queued' ? 'Preparando contenido…' : material.processingStatus === 'failed' ? 'Preparación pendiente · abre para reintentar' : material.analysisStatus === 'partial' ? 'Preparación parcial' : lastStudied ? `Último estudio: ${new Date(lastStudied).toLocaleDateString('es-PE')}` : 'Listo para estudiar'}</p><div className="material-footer"><span>Abrir material</span><b>→</b></div></button>
    <PopupMenu mobileSheet className="material-card-menu" label={`Opciones de ${material.title}`} trigger="···" triggerClass="context-menu-trigger" menuLabel={`Acciones de ${material.title}`}><button role="menuitem" onClick={onRename} disabled={material.deletionPending || material.processingStatus === 'processing' || material.processingStatus === 'queued'}>Renombrar</button><button role="menuitem" onClick={onArchive} disabled={material.deletionPending || material.processingStatus === 'processing' || material.processingStatus === 'queued'}>{material.archivedAt ? 'Restaurar material' : 'Archivar'}</button>{onDownload && <button role="menuitem" onClick={onDownload}>Descargar original</button>}<button role="menuitem" onClick={onDelete}>Eliminar</button></PopupMenu>
  </article>
}
